# variables:
#   IMAGE_NAME_CI: coko-server-ci
#   # SERVICE_NAME_DEPLOYMENT: waxdemo

# include:
#   - project: 'cokoapps/ci'
#     ref: main
#     file: 'ci-templates.yml'

# stages:
#   - Build
#   - Test

# build ci image:
#   extends: .build development
#   stage: Build
#   variables:
#     IMAGE_NAME: $IMAGE_NAME_CI
#     BUILD_PATH: .

# lint:
#   extends: .lint
#   stage: Test
#   variables:
#     IMAGE_NAME: $IMAGE_NAME_CI
#     WORKDIR: .
# test:
#   image: cokoapps/$IMAGE_NAME_CI:$CI_COMMIT_SHA
#   script:
#     - yarn jest

stages:
  - Lint
  - Test

lint:
  image: docker:23
  stage: Lint
  services:
    - docker:23-dind
  script:
    - yarn install --frozen-lockfile
    - yarn eslint .
    - yarn prettier --check .

test:
  image: docker:23
  stage: Test
  services:
    - docker:23-dind
  script: yarn test
