variables:
  IMAGE_NAME_CI: coko-server-ci

include:
  - project: 'cokoapps/ci'
    ref: main
    file: 'ci-templates.yml'

stages:
  # - Build
  - Test

# build ci image:
#   extends: .build development
#   stage: Build
#   variables:
#     IMAGE_NAME: $IMAGE_NAME_CI
#     BUILD_PATH: .

lint:
  # extends: .lint
  stage: Test
  image: cokoapps/coko-server-ci:909718fbc517cd6267f5cf4a6df80706b1bc040c
  script:
    - cd .
    - ls
    - ls node_modules
    - yarn eslint .
    - yarn prettier --check .
    - if [ ! -z "$STYLELINT" ]; then yarn stylelint "**/*.js"; fi
  # variables:
  #   IMAGE_NAME: $IMAGE_NAME_CI
  #   WORKDIR: .
# test:
#   image: cokoapps/$IMAGE_NAME_CI:$CI_COMMIT_SHA
#   script:
#     - yarn jest

# stages:
#   - Lint
#   - Test

# lint:
#   image: cokoapps/hhmi-dnn
#   stage: Lint
#   services:
#     - docker:23-dind
#   script:
#     - yarn lint

# test:
#   image: cokoapps/hhmi-dnn
#   stage: Test
#   services:
#     - docker:23-dind
#   script: yarn test
