version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-development
    depends_on:
      - db
      - filehosting
      - createbucket
    command: yarn jest --verbose --force-exit
    environment:
      - NODE_ENV=test
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-test_db}
      - POSTGRES_USER=${POSTGRES_USER:-test_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - PUBSWEET_SECRET=${PUBSWEET_SECRET:-theSecret}
      - S3_PROTOCOL=http
      - S3_HOST=filehosting
      - S3_PORT=${S3_PORT:-9000}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-cokoServerUser}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-superSecretUserPassword}
      - S3_BUCKET=${S3_BUCKET:-uploads}
    volumes:
      - ./dev:/home/node/app/dev
      - ./src:/home/node/app/src
      - ./authorization:/home/node/app/authorization

  db:
    extends:
      file: docker-compose.common.yml
      service: db

  filehosting:
    extends:
      file: docker-compose.common.yml
      service: filehosting

  createbucket:
    extends:
      file: docker-compose.common.yml
      service: createbucket

volumes:
  minio_storage:
